export const type = {
  CREATE: 'CREATE',
  CYPHER: 'CYPHERIFY',
  EXPRESSION: 'EXPRESSION',
  MATCH: 'MATCH',
  NODE: 'NODE',
  PATH: 'PATH',
  OPTIONAL_MATCH: 'OPTIONAL_MATCH',
  OUT: 'OUT',
  WHERE: 'WHERE'
}
